#!/usr/bin/env bash
# Bootstrap one scratch profile under a given DSH_HOME (ENV-1).
#
# WHY THIS EXISTS
# A reboot wipes /tmp, and the harness homes live there. `dsh --profile mcptest`
# then aborts, because a custom (non-template) profile name is **not**
# auto-initialized — `dsh-app-boot`'s `loadProfile()` throws
#   dsh: profile "mcptest" does not exist; create it with
#        'dsh plugin --profile mcptest add <package>'
# whenever `$DSH_HOME/profiles/mcptest/package.json` is missing. That is not a
# plugin defect, it is a missing host precondition — so it is scripted here.
#
# This script is idempotent, refuses the live home and the shared read-only
# baseline, and is also invoked by `install-scratch.sh`; on its own it is enough
# to make a wiped host bootable (it ends with a real composition check).
#
# WHY NOT LITERALLY `dsh plugin --profile mcptest add @deepseek-ai/dsh-base @deepseek-ai/dsh-headless`
# that command forwards to pnpm *inside the profile directory*, where
# `install-scratch.sh` has already created node_modules symlinks pointing into the
# plugin repository. A package manager that writes through such a link replaces
# real packages in the shared checkout with links into its own store — the hazard
# documented at the end of `harness/README.md`, which already damaged the npx
# installation once. The equivalent manifest written below yields the layout the
# launcher documents instead (two anchors: the bundle resolves from the dsh
# installation, and dsh's own `healProfilesModuleFallback()` links the dependency
# closure into `$DSH_HOME/profiles/node_modules` on the first real boot). If you
# really want the pnpm route, run it on a CLEAN profile directory, before
# `install-scratch.sh` creates the plugin links.
#
# Files in the profile directory once this script finishes:
#   package.json       — the profile manifest + dsh.profile.bundles (written here)
#   cordis.yml         — the profile-root entry list, generated BY DSH on the first
#                        compose ("the tree is composed as patches … Edit
#                        cordis.patch.yml, not this file")
#   cordis.patch.yml   — the profile's own user patch layer (written here, empty;
#                        `PROFILE_PATCH_FILENAME` in @deepseek-ai/dsh-app-boot).
#                        The launcher reads only this one as the user layer, and
#                        `cordis.yml` is the file DSH regenerates when missing — so
#                        both are asserted below instead of being guessed.
set -euo pipefail

log() { printf '[bootstrap-profile] %s\n' "$*"; }
warn() { printf '[bootstrap-profile] WARN: %s\n' "$*" >&2; }
fail() {
  printf '[bootstrap-profile] FATAL: %s\n' "$*" >&2
  printf '[bootstrap-profile] recovery steps: plugins/dsh-mcp-session/harness/README.md § "Profile bootstrap & ENV-1 recovery"\n' >&2
  exit 1
}

# §5.2: one DSH_HOME per member. Precedence:
#   DSH_SCRATCH (explicit harness override, legacy)  >  DSH_HOME (unless it is
#   the LIVE home, which the ambient DSH session always exports)  >  default.
LIVE_HOME="${HOME}/.dsh"
DEFAULT_HOME="/tmp/ms-eng-scratch"
if [[ -n "${DSH_SCRATCH:-}" ]]; then
  HOME_DIR="$DSH_SCRATCH"
elif [[ -n "${DSH_HOME:-}" && "$DSH_HOME" != "$LIVE_HOME" ]]; then
  HOME_DIR="$DSH_HOME"
else
  HOME_DIR="$DEFAULT_HOME"
fi
if [[ "$HOME_DIR" == "$LIVE_HOME" || "$HOME_DIR" == "$HOME/.dsh"* ]]; then
  echo "refusing to bootstrap the live DSH home: $HOME_DIR" >&2
  exit 1
fi
if [[ "$HOME_DIR" == "/tmp/dsh-scratch" && "${MS_ALLOW_SHARED_HOME:-}" != "1" ]]; then
  echo "refusing to write the shared read-only baseline /tmp/dsh-scratch (use DSH_HOME=<your own home>, or set MS_ALLOW_SHARED_HOME=1)" >&2
  exit 1
fi
SCRATCH="$HOME_DIR"

# `DSH_PROFILE` is accepted as either a profile NAME (`mcptest`, i.e.
# `$DSH_HOME/profiles/mcptest`) or a PATH (the harness scripts pass a path).
case "${DSH_PROFILE:-}" in
  "") PROFILE="$SCRATCH/profiles/mcptest" ;;
  */*) PROFILE="$DSH_PROFILE" ;;
  *) PROFILE="$SCRATCH/profiles/$DSH_PROFILE" ;;
esac
PROFILE_NAME="$(basename "$PROFILE")"
PROFILES_DIR="$(dirname "$PROFILE")"
BOOTSTRAP_LOG="${MS_BOOTSTRAP_LOG:-$SCRATCH/.bootstrap-profile.log}"

command -v dsh >/dev/null 2>&1 \
  || fail "dsh is not on PATH, so the profile cannot be checked at all. Install DSH (or fix PATH) and re-run."

# --- 1. profile manifest (the launcher's hard precondition) -------------------
# `mkdir -p` also creates the whole home tree: /tmp is wiped by reboots (observed
# repeatedly on 2026-09-13), so `$DSH_HOME` may not exist at all — this is the
# "from zero, directory included" path.
[[ -d "$SCRATCH" ]] || log "scratch home did not exist — creating the whole tree: $SCRATCH"
mkdir -p "$PROFILE/node_modules" "$PROFILES_DIR" \
  || fail "cannot create the profile directory $PROFILE (permissions? is \$DSH_HOME writable?)."

if [[ -f "$PROFILE/package.json" ]]; then
  node - "$PROFILE/package.json" <<'NODE' \
    || fail "the existing profile manifest $PROFILE/package.json does not declare a non-empty dsh.profile.bundles[] (dsh would boot an empty tree). Delete the file and re-run, or restore the skeleton."
const manifest = JSON.parse(require('node:fs').readFileSync(process.argv[2], 'utf8'))
const bundles = manifest?.dsh?.profile?.bundles
if (!Array.isArray(bundles) || bundles.length === 0) process.exit(3)
NODE
  log "profile manifest already present and valid: $PROFILE/package.json (idempotent: nothing rewritten)"
else
  cat > "$PROFILE/package.json" <<'JSON'
{
  "name": "dsh-profile-mcptest",
  "private": true,
  "dsh": { "profile": { "bundles": ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-headless"] } }
}
JSON
  log "created profile manifest: $PROFILE/package.json (bundles: @deepseek-ai/dsh-base, @deepseek-ai/dsh-headless)"
fi

# --- 2. the profile's own patch layer ----------------------------------------
# The launcher reads `cordis.patch.yml` as the user layer applied AFTER the bundle
# patches; an absent file means "no user patches". An empty list is written so the
# place for user overrides is visible and survives a hand-edit cycle. (`cordis.yml`
# — the profile-root entry list — is generated by dsh itself, see the header.)
LAYER="$PROFILE/cordis.patch.yml"
if [[ ! -f "$LAYER" ]]; then
  printf '# %s — the profile user patch layer (empty). Bundle patches are applied\n# first; a --patch overlay is applied after this file.\n[]\n' "$PROFILE_NAME" > "$LAYER"
  log "created empty profile layer: $LAYER"
fi

# --- 3. module farm ----------------------------------------------------------
# `$PROFILES_DIR/node_modules` is OWNED BY DSH: `healProfilesModuleFallback()` (called
# on every real boot, not on --dump-config) mkdirs it and links the installation
# dependency closure into it. Never pre-create it here:
#   * a symlink to another home makes dsh write its links into THAT home;
#   * a symlink whose target is gone makes every launch die with a bare
#     `ENOENT: no such file or directory, mkdir '<home>/profiles/node_modules'`.
# So a symlink found here is removed and left to dsh.
FARM="$PROFILES_DIR/node_modules"
if [[ -L "$FARM" ]]; then
  warn "removing the module-farm symlink $FARM -> $(readlink "$FARM" 2>/dev/null || echo '?'): dsh owns that directory, and a link (dangling or not) breaks the boot. dsh recreates it from its installation anchor on the next boot."
  rm -f "$FARM" || fail "cannot remove the broken module farm $FARM (permissions?)."
fi
if [[ -e "$FARM" && ! -d "$FARM" ]]; then
  fail "$FARM exists and is not a directory; dsh needs to own it. Remove it and re-run."
fi
# LOUD when it is missing: /tmp gets wiped, so this is the normal post-reboot
# state, not an error — but it must never pass silently, because a missing farm
# plus a missing installation anchor is exactly how "the whole team's harness
# stopped booting" started. Give the recovery command (with the home pinned).
if [[ ! -d "$FARM" ]]; then
  warn "module farm absent at $FARM — NOT an error: dsh's healProfilesModuleFallback() re-creates it from the installation anchor on the first real boot."
  warn "  if the installation anchor is unavailable too, restore the bundles into the profile instead — with the home PINNED (a bare 'dsh plugin …' writes the LIVE ~/.dsh):"
  warn "    DSH_HOME=$SCRATCH dsh plugin --profile $PROFILE_NAME add @deepseek-ai/dsh-base @deepseek-ai/dsh-headless"
fi

# --- 4. prove it composes (no model call, no overlay needed) -----------------
# `--dump-default-config` = bundles only: it resolves every `dsh.profile.bundles`
# entry to its patch layer and composes the tree, which is exactly the bootstrap
# contract. It needs nothing from install-scratch.sh, so this script is usable on
# its own.
#
# ENV-1b HARD RULE (2026-09-13 incident): EVERY `dsh` call in this directory pins
# DSH_HOME explicitly — never inherit it. A bare `dsh plugin --profile <name>` (or
# any `dsh` call without DSH_HOME) runs against the LIVE home and rewrites
# `~/.dsh/profiles/<name>/cordis.yml`; that happened at 17:02:30 while the exact
# "bootstrap command" was being checked. Audit every call site with:
#   grep -n 'DSH_HOME="\$SCRATCH" dsh' harness/*.sh
[[ -n "${SCRATCH:-}" && "$SCRATCH" != "$LIVE_HOME" && "$SCRATCH" != "/tmp/dsh-scratch" ]] \
  || fail "refusing to run dsh: DSH_HOME resolved to '${SCRATCH:-<unset>}'. Pin it to a throwaway home (DSH_HOME=/tmp/<you>-scratch) — a bare 'dsh plugin --profile <name>' rewrites the LIVE ~/.dsh/profiles/<name>."
if ! DSH_HOME="$SCRATCH" dsh --profile "$PROFILE_NAME" --dump-default-config >"$BOOTSTRAP_LOG" 2>&1; then
  printf '%s\n' "--- dsh --profile $PROFILE_NAME --dump-default-config (tail) ---" >&2
  tail -30 "$BOOTSTRAP_LOG" >&2 || true
  fail "profile $PROFILE_NAME does not compose; see the dsh output above (full log: $BOOTSTRAP_LOG)."
fi
grep -q '^- id:' "$BOOTSTRAP_LOG" \
  || fail "dsh reported success but composed no entries (log: $BOOTSTRAP_LOG)."

# The compose above is also what makes dsh generate the profile-root `cordis.yml`;
# assert the whole documented profile layout instead of assuming it.
for required in package.json cordis.yml cordis.patch.yml; do
  [[ -e "$PROFILE/$required" ]] \
    || fail "the bootstrap did not produce $PROFILE/$required (profile layout incomplete; log: $BOOTSTRAP_LOG)."
done

log "profile '$PROFILE_NAME' ready at $PROFILE ($(grep -c '^- id:' "$BOOTSTRAP_LOG" || true) composed entries; package.json + cordis.yml + cordis.patch.yml present) — log: $BOOTSTRAP_LOG"
echo "next: DSH_HOME=$SCRATCH bash $(dirname "${BASH_SOURCE[0]}")/install-scratch.sh"
