#!/usr/bin/env bash
# Bootstrap + install dsh-mcp-session and the harness probes into the isolated host.
#
# Never touches the live profile: everything lands under the member's own
# throwaway DSH_HOME (§5.2). Precedence: DSH_SCRATCH > DSH_HOME (unless it is the
# live ~/.dsh) > /tmp/ms-eng-scratch; ~/.dsh and the shared read-only baseline
# /tmp/dsh-scratch are refused.
#
# ENV-1 (r5b) — this script is the supported way to (re)create a scratch host,
# because /tmp is wiped by a reboot and the old shared baseline may simply be
# gone. It therefore
#   1. runs `bootstrap-profile.sh`, which script-creates the profile skeleton
#      (<home>/profiles/<name>/package.json — dsh throws `profile "X" does not
#      exist` without it; `cordis.yml` is generated by dsh on the first compose)
#      and repairs the module farm;
#   2. repairs a foreign or DANGLING <home>/profiles/node_modules link. That
#      directory is owned by dsh (`healProfilesModuleFallback`, called on every
#      real boot): a link to another home makes dsh write into THAT home, and a
#      link left dangling after its target disappears makes every launch die with
#      `ENOENT: no such file or directory, mkdir '<home>/profiles/node_modules'`
#      — a message that names neither the cause nor the fix. This script never
#      creates that path; dsh populates it from the installation anchor.
#   3. fails LOUDLY, naming the fix, on every precondition it can check — instead
#      of letting dsh report an unrelated-looking ENOENT/crash later;
#   4. proves the profile really composes (`dsh --dump-config`, no model call,
#      no token) before it declares success.
set -euo pipefail

log() { printf '[install-scratch] %s\n' "$*"; }
warn() { printf '[install-scratch] WARN: %s\n' "$*" >&2; }
fail() {
  printf '[install-scratch] FATAL: %s\n' "$*" >&2
  printf '[install-scratch] recovery steps: plugins/dsh-mcp-session/harness/README.md § "Profile bootstrap & ENV-1 recovery"\n' >&2
  exit 1
}

PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# §5.2: one DSH_HOME per member. Precedence:
#   DSH_SCRATCH (explicit harness override, legacy)  >  DSH_HOME (unless it is
#   the LIVE home, which the ambient DSH session always exports)  >  default.
# The live home and the shared read-only baseline /tmp/dsh-scratch are refused.
LIVE_HOME="${HOME}/.dsh"
DEFAULT_HOME="/tmp/ms-eng-scratch"
if [[ -n "${DSH_SCRATCH:-}" ]]; then
  HOME_DIR="$DSH_SCRATCH"
elif [[ -n "${DSH_HOME:-}" && "$DSH_HOME" != "$LIVE_HOME" ]]; then
  HOME_DIR="$DSH_HOME"
else
  HOME_DIR="$DEFAULT_HOME"
fi
if [[ "$HOME_DIR" == "$LIVE_HOME" ]]; then
  echo "refusing to install into the live DSH home: $HOME_DIR" >&2
  exit 1
fi
if [[ "$HOME_DIR" == "/tmp/dsh-scratch" && "${MS_ALLOW_SHARED_HOME:-}" != "1" ]]; then
  echo "refusing to write the shared read-only baseline /tmp/dsh-scratch (use DSH_HOME=<your own home>, or set MS_ALLOW_SHARED_HOME=1)" >&2
  exit 1
fi
SCRATCH="$HOME_DIR"
PROFILE="${DSH_PROFILE:-$SCRATCH/profiles/mcptest}"
PATCH_FILE="${MS_PATCH:-/tmp/ms-smoke.yml}"
# Harness-private copy of the canonical config. A shared home is also used by
# other agents' probes, which rewrite mcp-session.json (e.g.
# `hintScan.maxServers: 1` or `proxyTool: false`); the driver restores from this
# private copy instead of trusting whatever it finds.
CANONICAL_FILE="${MS_CANONICAL:-/tmp/ms-harness-canonical.json}"

if [[ "$SCRATCH" == "$HOME/.dsh"* ]]; then
  echo "refusing to install into the live DSH home: $SCRATCH" >&2
  exit 1
fi

# ---------------------------------------------------------------- preconditions
command -v dsh >/dev/null 2>&1 \
  || fail "dsh is not on PATH; nothing can boot the scratch host. Install DSH (or fix PATH) and re-run."
command -v node >/dev/null 2>&1 \
  || fail "node is not on PATH; the harness driver and the mutation check need it. Fix PATH and re-run."
[[ -f "$PLUGIN_DIR/package.json" ]] \
  || fail "$PLUGIN_DIR/package.json is missing — PLUGIN_DIR resolved to $PLUGIN_DIR, which is not the plugin root."
for built in lib/index.js lib/manager.js; do
  [[ -f "$PLUGIN_DIR/$built" ]] \
    || fail "$PLUGIN_DIR/$built is missing: the plugin is not built. Run 'pnpm build' in $PLUGIN_DIR and re-run."
done

# ------------------------------------------------------- profile bootstrap
# ENV-1: the profile skeleton, the manifest check and the module-farm repair live
# in `bootstrap-profile.sh` — a standalone, idempotent, contract-named script that
# this installer calls. It refuses the live home / shared baseline itself, and the
# resolved paths are exported so it cannot disagree about which home is meant.
PROFILES_DIR="$(dirname "$PROFILE")"
SHARED_HOME="${MS_SHARED_HOME:-/tmp/dsh-scratch}"
DSH_HOME="$SCRATCH" DSH_PROFILE="$PROFILE" MS_SHARED_HOME="$SHARED_HOME" \
  bash "$(dirname "${BASH_SOURCE[0]}")/bootstrap-profile.sh" >&2 \
  || fail "profile bootstrap failed (see the bootstrap-profile.sh output above)."

# Optional host config (settings/credentials). Not required by the harness: the
# driver parks the turn before any provider call, so no model call is issued.
# /tmp is wiped by reboots, so the donor home may simply be gone — say so once,
# loudly, instead of leaving the reader to infer it.
[[ -d "$SHARED_HOME" ]] || log "shared donor home $SHARED_HOME does not exist (/tmp was wiped?) — fine for the harness (zero model calls); nothing is hidden by this."
for shared_file in settings.yaml .credentials.yaml; do
  if [[ -f "$SCRATCH/$shared_file" ]]; then
    continue
  elif [[ -f "$SHARED_HOME/$shared_file" ]]; then
    cp "$SHARED_HOME/$shared_file" "$SCRATCH/$shared_file"
  else
    warn "no $shared_file in $SCRATCH and none to borrow from $SHARED_HOME; fine for the harness (zero model calls), but a real turn on this host would have no model config."
  fi
done

# ----------------------------------------------------------------- plugin links
ln -sfn "$PLUGIN_DIR" "$PROFILE/node_modules/dsh-mcp-session"
ln -sfn "$PLUGIN_DIR/harness/fake-mcp" "$PROFILE/node_modules/dsh-fake-mcp"
ln -sfn "$PLUGIN_DIR/harness/verify" "$PROFILE/node_modules/dsh-ms-verify"
for name in dsh-mcp-session dsh-fake-mcp dsh-ms-verify; do
  [[ -f "$PROFILE/node_modules/$name/package.json" ]] \
    || fail "what should be $PROFILE/node_modules/$name/package.json does not resolve — the overlay would fail with 'Cannot find package \"$name\"'."
done

# ------------------------------------------------------------------- scratch cfg
cat > "$SCRATCH/mcp-session.json" <<'JSON'
{
  "defaultPolicy": "lazy",
  "keywordReveal": true,
  "proxyTool": true,
  "hintScan": { "maxServers": 3 },
  "catalog": true,
  "servers": {
    "amap": { "label": "高德地图", "hints": ["高德", "地图", "地址", "路线", "天气", "导航", "在哪", "坐标"] },
    "xiaohongshu": { "label": "小红书", "hints": ["小红书", "笔记", "攻略", "种草"] },
    "obsidian": { "label": "Obsidian 知识库", "hints": ["知识库", "笔记库", "obsidian"] }
  }
}
JSON
cp "$SCRATCH/mcp-session.json" "$CANONICAL_FILE"

cat > "$PATCH_FILE" <<'YAML'
# Harness overlay for dsh-mcp-session (isolated host only).
- insert:
    - id: fake-mcp
      name: dsh-fake-mcp
    - id: mcp-session
      name: dsh-mcp-session
      config: {}
    - id: ms-verify
      name: dsh-ms-verify
YAML

# --------------------------------------------------- prove the profile composes
# `--dump-config` loads the profile manifest, resolves every bundle to its patch
# layer and applies the overlay — the whole bootstrap path except the runtime
# module resolution. Zero model calls, no tokens, ~1s. Skip with MS_SKIP_VERIFY=1.
PROFILE_NAME="$(basename "$PROFILE")"
VERIFY_LOG="${MS_VERIFY_LOG:-$SCRATCH/.install-scratch-verify.log}"
if [[ "${MS_SKIP_VERIFY:-0}" != "1" ]]; then
  # ENV-1b HARD RULE: this call pins DSH_HOME explicitly (never inherit) — a bare
  # `dsh plugin --profile <name>` rewrites the LIVE ~/.dsh/profiles/<name>. Audit:
  #   grep -n 'DSH_HOME="\$SCRATCH" dsh' harness/*.sh
  [[ -n "${SCRATCH:-}" && "$SCRATCH" != "$LIVE_HOME" && "$SCRATCH" != "/tmp/dsh-scratch" ]] \
    || fail "refusing to run dsh: DSH_HOME resolved to '${SCRATCH:-<unset>}'. Pin it to a throwaway home — a bare 'dsh plugin --profile <name>' rewrites the LIVE ~/.dsh/profiles/<name>."
  if ! DSH_HOME="$SCRATCH" dsh --profile "$PROFILE_NAME" --patch "$PATCH_FILE" --dump-config >"$VERIFY_LOG" 2>&1; then
    printf '%s\n' "--- dsh --profile $PROFILE_NAME --dump-config (tail) ---" >&2
    tail -30 "$VERIFY_LOG" >&2 || true
    fail "the profile does not compose; see the dsh output above (full log: $VERIFY_LOG)."
  fi
  for entry in fake-mcp mcp-session ms-verify; do
    grep -q "id: $entry" "$VERIFY_LOG" \
      || fail "the composed tree has no entry '$entry' — the overlay $PATCH_FILE did not land (log: $VERIFY_LOG)."
  done
  log "profile composes: $(grep -c '^- id:' "$VERIFY_LOG" || true) top-level entries incl. fake-mcp/mcp-session/ms-verify (log: $VERIFY_LOG)"
else
  log "skipped the compose check (MS_SKIP_VERIFY=1); $VERIFY_LOG not written"
fi

log "installed:"
echo "  plugin  -> $PROFILE/node_modules/dsh-mcp-session"
echo "  config  -> $SCRATCH/mcp-session.json"
echo "  canonical snapshot -> $CANONICAL_FILE"
echo "  overlay -> $PATCH_FILE"
echo
echo "run: DSH_HOME=$SCRATCH dsh --profile $PROFILE_NAME --patch $PATCH_FILE smoke"
